### ISSUE TITLE
Remove Github Action checkout token $((secrets.SUB_MODULE_PATH}}

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/node-sdk#56]
To enable Github security dependency analysis feature 'Dependabot' we need to remove the Github secrets tokens so Dependabot can run when making a PR with updated dependencies.

```
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{secrets.SUB_MODULE_PAT}}
        submodules: recursive
```

https://github.com/nitrictech/node-sdk/blob/main/.github/workflows/test.yaml

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1dynk75) by [Unito](https://www.unito.io)
